### ISSUE TITLE
toHaveTextContent("") matches element with non-empty content

### ISSUE THREAD

**Issue by alexkrolick** [testing-library/jest-dom#104]
v3.2.2

```js
const el = document.createElement("div")
el.textContent = "0"
expect(el).toHaveTextContent("") // passes, should be error
```

**Comment by alexkrolick** [comment]
Will add a repro test case, the example I tried passed (unexpectedly)

**Comment by gnapse** [comment]
Is this happening only with the string `"0"`? Because from the code I think any string will match `.toHaveTextContent('')`. This is all ultimately determined [here](https://github.com/testing-library/jest-dom/blob/b2b4bd3ba65c48b350194a7623797e70f8a1390e/src/utils.js#L119), and any string `.includes('')`.

**Comment by alexkrolick** [comment]
Ah, indeed, it fails to throw for other strings.

**Comment by alexkrolick** [comment]
I don't think it should use `includes` here - use a regex for partial matches, or something like `toContainText`
