### ISSUE TITLE
Match on attributes from animation keyframes

### ISSUE THREAD

**Issue by cdfa** [testing-library/jest-dom#124]
### Describe the feature you'd like:

At the moment, it seems like CSS attributes from `@keyframes` are not included in the checks of `toBeVisible` (or in general probably). It would be very nice if there was a way to do this to test dynamic animations.

### Describe alternatives you've considered:

I really don't know any.

### Teachability, Documentation, Adoption, Migration Strategy:

The behaviour could be hidden under a toggle or separate matcher, but I think it makes most sense to make it the default.

**Comment by gnapse** [comment]
I'd like to see a more concrete proposal of what you mean, because I really do not see how could this be actionable. From what I understand, `@keyframes` are declared separately, and then you apply it in a css selector rule in the form of the `animation-name` css property.

```css
@keyframes effect-fade-in {
    from { opacity: 0; }
    to { opacity: 1; }
}

.fade-in {
    animation-name: effect-fade-in;
    animation-duration: 80ms;
}
```

Can't you just check that elements have the `fade-in` class? Or (if you've loaded the css stylesheet in the document in the test environment) that the element passes a test along the lines of

```js
expect(element).toHaveStyle("animation-name: effect-fade-in")
```

If what you mean is to validate the the element has a certain opacity, then I'm not sure how would you accomplish this. The opacity changes dynamically over a preriod of 80ms, and IMO this will not only be pointless to test, it will not be easy to achieve. I'm not even sure what the custom matcher interface would be, and this would need extensive support from jsdom to make it work. After all all our checks rely on the DOM api to provide us with the data for us to test.

**Comment by gnapse** [comment]
I'm going to be closing this. Feel free to reopen if I got it wrong, or if you have a concrete implementation plan and custom matcher proposal, and jsdom supports anything we might need from it.

**Comment by cdfa** [comment]
A concrete example of such a dynamic animation is one where an element turns outward (or inward depending on your POV) in 3D, like in [this codepen](https://codepen.io/noeldelgado/pen/pGwFx) (I'm porting it to React). It needs to be dynamic, because the angle at which the element needs to turn depends on the width of the "perspective element".

Anyway this means I generate the `@keyframes` with JS (I'm using `styled-components` for this) and I would like to test that the element has the right style at the end of the animation.

As for implementation: I'm really no expert in this area, so creating a concrete implementation plan would be to difficult, but I think it should be possible using [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)

**Comment by gnapse** [comment]
Hmmmm, the thing is, typically in the jest test environment you usually do not have the actual stylesheet loaded into the document as you'd normally have in the actual browser environment. You'd have to do something manually and explicit to attach a stylesheet to the `document` before `getComputedStyle` in that environment actually returns you all the styles of an element, taking into consideration the ones that it gets via its class names from the stylesheet.

With `styled-components` this gets even trickier, because I'm not even sure how you'd have access in the test environment to the dynamically generated stylesheet that `styled-components` provides. I'm not even sure if `styled-components` in the limited scope of tests even generates this stylesheet at all. Even if they do, what it probably does is to dynamically add `<link rel="stylesheet" />` to the html `<head/>`. But that does not work as expected in the jsdom environment, at least not out of the box.

See [this comment](https://github.com/testing-library/jest-dom/issues/113#issuecomment-496971128) I posted on another issue that needed to rely on the same stuff I'm talking about here.

If you devise a way to have the dynamically generated stylesheet from styled-components available and attached to the document during the jest tests, we might be able to work on this and that other issue, to see if there's something jest-dom could do to make it all easier.

**Comment by cdfa** [comment]
Hmm, thanks for the pointer to that comment. Too bad this is so complicated :(

I don't think `jest-styled-components` takes the styling from `keyframes` into account, but I'll try anyway.

Thanks for the quick responses!
