### ISSUE TITLE
Cannot run in Node using jsdom fragment due to missing global window object

### ISSUE THREAD

**Issue by msendlakowski** [testing-library/jest-dom#142]
- `@testing-library/jest-dom` version: 4.1.2
- `node` version: 10.15.0
- `npm` (or `yarn`) version: yarn 1.13.0

### Relevant code or config:

```js
expect(getByTestId('testid')).toHaveAttribute('disabled')
```

### What you did:

Running a test in a node environment using a JSDOM fragment rather than a full JSDOM container.  (This was produced by https://github.com/marko-js/testing-library)

### What happened:

Got the following error:
```
received value must be an HTMLElement or an SVGElement.
Received has type:  object
```

I tracked it down to this line:
https://github.com/testing-library/jest-dom/blob/master/src/utils.js#L47

There is no defaultView object defined when using a JSDOM fragement.
This is also mentioned in https://github.com/testing-library/dom-testing-library/pull/377, where they question the need to have a window object:

It seems like a valid question. Does jest-dom need to require a global window object?

### Problem description:

Cannot use jest-dom within node when using a JSDOM fragment

### Suggested solution:

Remove the requirement for having a defaultView.  Or get dom-testing-library to add one.

**Comment by kentcdodds** [comment]
I'm thinking that the issue here is that the DOM element is not attached to the document which is why this is a problem. I hadn't considered that issue coming up, but it makes sense.

I'm not sure what to do about this. I *think* this would be solved if we just required that everyone using these libraries have a globally accessible `window` and `document` so we didn't have to retrieve that from the DOM elements.

cc @eps1lon thoughts?

**Comment by DylanPiercey** [comment]
@kentcdodds another option would be to walk the constructors prototype chain and check for the name `"HTMLElement"` or `"SVGElement"` like so:

```
function checkHtmlElement(htmlElement, ...args) {
  if (
    !instanceOf(htmlElement, 'HTMLElement') &&
    !instanceOf(htmlElement, 'SVGElement')
  ) {
    throw new HtmlElementTypeError(htmlElement, ...args)
  }
}

function instanceOf(obj, name) {
  if (obj) {
    let constructor = obj.constructor
    while (constructor) {
      if (constructor.name === name) {
        return true
      }

      constructor = Object.getPrototypeOf(constructor)
    }
  }

  return false
}
```

But this issue would also present itself in `toBeVisible` and `toHaveStyle`.
I think the simplest approach for us from the `@marko/testing-library` side of things would just be to not use `JSDOM.fragment` for testing the server rendered markup. This is somewhat lame since In my opinion server side tests shouldn't be able to interact with the window or trigger events (those should happen in a browser context, not on the server side), but at least it would work for the basic cases and require less work on the side of `jest-dom`.

I would prefer the `window` and `document` not to be required globally as this is going to cause the tests in our case to expose these globals even though we are only using jsdom to do some validation on html strings.

**Comment by kentcdodds** [comment]
I'm fine with that personally.

**Comment by msendlakowski** [comment]
That works for me too. Thanks @DylanPiercey .
I'll let @kentcdodds close the issue, if you think its not a blocker for other cases where someone may use a JSDOM fragment.

**Comment by DylanPiercey** [comment]
Released `@marko/testing-library@2.1.0` which ensures there is a `defaultView`. So it's all good on our side of things 😄.

**Comment by kentcdodds** [comment]
Looks ok 👍

**Comment by eps1lon** [comment]
This is my current stance:

1. Please follow installation instructions of the library you use. In particular with `jsdom`
> Note that we strongly advise against trying to "execute scripts" by mashing together the jsdom and Node global environments (e.g. by doing global.window = dom.window), and then executing scripts or test code inside the Node global environment. Instead, you should treat jsdom like you would a browser, and run all scripts and tests that need access to a DOM inside the jsdom environment, using window.eval or runScripts: "dangerously". This might require, for example, creating a browserify bundle to execute as a <script> element—just like you would in a browser.

> Finally, for advanced use cases you can use the dom.runVMScript(script) method, documented below.

2. If not the burden is on your code to make it compatible with the library you use. Since this library is targetted at the DOM, you have to provide that environment (usual by running in a browser). I totally get that this requires way too much setup and `jsdom` is a god-send. But it's hard for me to understand how making `window` a global variable is not possible.

**Comment by DylanPiercey** [comment]
@eps1lon I agree 100% with the stance of jsdom that you shouldn’t mash together the jsdom global is into nodejs and should instead use bundlers or whatever is needed to actually execute scripts in the jsdom VM.

The use case above and what we are recommending for @marko/testing-library is that when testing components which are only rendered on the server side you should only be making assertions against the dom, not firing events or relying on any JavaScript running in the jsdom context.

I understand supporting this use case requires a bit more effort from this library but it is useful to be able to make similar assertions for dom structure in both nodejs based string rendering tests and in tests running in the actual browser context.

I’ll also add that relying on the window being a global or any global from the window being in scope of these utilities would also cause issues when testing data within iframe and probably some other use cases.

**Comment by eps1lon** [comment]
> I’ll also add that relying on the window being a global or any global from the window being in scope of these utilities would also cause issues when testing data within iframes and probably some other use cases.

So far I only know of `instanceof` problems in which case you always have a node to compare against.

I'll take a look at how one would test server rendered markup. My guess is that you just pass that to `jsdom` and let your test execute in the same environment. Which is what `jsdom` is recommending in the first place. We just got so used to mashing these together and never considered if this is actually correct.

For example if we want to create an event we need to have access to some window object. Where else would we get the constructors? If you only expose some `fireEvent` helper that needs the event target then it kind of works but not if you expose (and use internally) some `createEvent`.

**Comment by DylanPiercey** [comment]
The `instanceof` issue is what I was thinking of. By using `defaultView` we get the constructors based off of the current node which is good. If we relied on the global window then this would break in iframes.

Regarding events, at least with the Marko setup, we assume that no event handlers should be setup (hydration has not run) when testing the server side render. I’ve actually set this up to error when using `fireEvent` on the server side to avoid this confusion (https://github.com/marko-js/testing-library/blob/master/src/shared.ts#L75).

**Comment by eps1lon** [comment]
Makes sense. Thanks for providing more context. I think this is a better requirement for us: make it useable for server side stuff (i.e. everything solely relying on markup) and then require a browser environment for client side stuff (e.g. firing events).
