### ISSUE TITLE
Add documentation about transitioning from Enzyme

### ISSUE THREAD

**Issue by fullstackzach** [testing-library/jest-dom#208]
- `@testing-library/jest-dom` version: 5.1.1
- `node` version: v12.13.1
- `npm` (or `yarn`) version: npm v6.12.1

### Relevant code or config:

```js
import 'jest-enzyme'
import Enzyme from 'enzyme'
import Adapter from 'enzyme-adapter-react-16'
import 'jest-styled-components'
import { configure } from '@testing-library/dom'
import '@testing-library/jest-dom/extend-expect'

Enzyme.configure({ adapter: new Adapter() })

configure({ testIdAttribute: 'data-test-id' })
```

### What you did:

I was trying to move `import '@testing-library/jest-dom/extend-expect'` from individual *.test.js files to our test-setup.js file.

### What happened:

We are working on migrating from Enzyme to react-testing-library and use the jest-dom/extend-expect library in quite a few files. I was trying to centralize this in our test-setup.js

Once I moved `import '@testing-library/jest-dom/extend-expect'` to our test-setup.js, I found it broke some enzyme tests.

### Problem description:

I found that since some matchers are redefined by jest-dom, which breaks some Enzyme tests with messaging like this that is kind of unclear:

```
 ● RadioButton › sets disabled state

    expect(received).toBeDisabled()

    received value must be an HTMLElement or an SVGElement.
    Received has type:  object
    Received has value: {}

      27 |   test('sets disabled state', () => {
      28 |     const wrapper = shallow(<RadioButton theme={theme} disabled />)
    > 29 |     expect(wrapper.find('RadioButton__Input')).toBeDisabled()
         |                                                ^
      30 |   })
      31 |
      32 |   test('highlights focus on tab/arrow keys', () => {

      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:380:30)
      at Object.toBeDisabled (node_modules/expect/build/index.js:381:15)
      at Object.<anonymous> (src/components/RadioButton/RadioButton.test.js:29:48)

```

Here's a screenshot of vscode pointing an enzyme test using toBeDisabled() to the jest-dom matcher

![image](https://user-images.githubusercontent.com/13011363/74749284-89f9a000-522f-11ea-9b35-3ffaceaa6536.png)

### Suggested solution:

I think it would be good to add documentation that `import '@testing-library/jest-dom/extend-expect'` has to be individually included in each *.test.js file if Enzyme is also in this project. (Or a is there a different way to globally configure it?)  For situations like ours where we are working on transitioning.

**Comment by gnapse** [comment]
Interesting. Makes sense, but...

To be clear, this is not because of being using Enzyme per-se, but because of the use of `jest-enzyme`.

Not sure where to put this in the documentation. This library is not particular of React, it's for testing the DOM in general. So a particular dedicated reference to Enzyme seems unjustified.

Also, this conflict of matchers naming could happen with other jest custom matchers you may be importing as well. This is not exclusive about the fact of being migrating from Enzyme. For example, [`jest-extended` also provides a `toBeEmpty`](https://github.com/jest-community/jest-extended#tobeempty) with a purpose different than ours.

I noticed this a long while ago and opened [this issue in the jest repo](https://github.com/facebook/jest/issues/6243), because IMO this is a wider issue that's ultimately on jest: the namespace of matchers is global.

**Comment by fullstackzach** [comment]
Gotcha. That makes sense. I think this issue could serve as good enough documentation if someone comes searching.
