### ISSUE TITLE
`toBeDisabled` to support `aria-disabled`

### ISSUE THREAD

**Issue by wongm3** [testing-library/jest-dom#230]
### Describe the feature you'd like:

With a11y suggesting removing the native 'disabled' attribute, I was hoping `toBeDisabled` could check for `aria-disabled` attribute to be true as well.

### Suggested implementation:

Adding a check for `aria-disabled` is true within `isElementDisabled`.

### Describe alternatives you've considered:

Currently we use `.toHaveAttribute('aria-disabled', 'true')`, but would be nice to be able to use `.toBeDisabled()`

### Teachability, Documentation, Adoption, Migration Strategy:

Here are some links for more detail on `aria-disabled`:
- https://a11y-101.com/development/aria-disabled
- https://a11ysupport.io/tests/html_button(type-button--aria-disabled-true)

**Comment by wongm3** [comment]
I would also like to attempt to add this feature, and will be looking to create a PR for this.

**Comment by gnapse** [comment]
This seems a duplicate of #144 where we discussed this at length and decided not to do it. Check out that discussion and let me know if you understand and agree on the reasons why.

I won't close it because my suggestion now would be to add a note about this in the README in the documentation for `toBeDisabled` to be explicit about it.

**Comment by wongm3** [comment]
I think that makes sense and I will close out the issue.
