### ISSUE TITLE
 document.execCommand is not a function

### ISSUE THREAD

**Issue by VeereshKumar14** [testing-library/jest-dom#234]
- `@testing-library/jest-dom` version: 4.0.0
- `node` version: 10.16.0
- `npm` (or `yarn`) version: 6.13.6

### Relevant code or config:

```js
document.execCommand('copy');
```

### What you did:
 When try to test document.execCommand('copy');

### What happened:
 It returns like TypeError: document.execCommand is not a function

### Reproduction:
Try with document.execCommand('copy'); in a on click event for an input field and test.

**Comment by gnapse** [comment]
Not sure what this issue has to do with `jest-dom`. Did you have some issue with some of the custom jest matchers this library provides? Otherwise, I'm afraid this is not the right place to report this. Sounds like a core DOM functionality that is probably missing in `jsdom`. I'd suggest you search in [jsdom's issues](https://github.com/jsdom/jsdom/issues) first. (jsdom is the browser-like DOM implementation made in js and used to run the DOM rendered in a headless test environment when using `jest`).
