### ISSUE TITLE
toBeDisabled() does not work with latest @rmwc/dialog

### ISSUE THREAD

**Issue by pahan35** [testing-library/jest-dom#283]
- `@testing-library/jest-dom` version: 5.11.1
- `node` version: 13.7.0
- `npm` (or `yarn`) version: 6.14.7

* `@testing-library/dom` version: 7.21.4
* `@testing-library/react` version: 10.4.7

### Relevant code or config:

```js
import React, {useContext} from 'react'
import {DialogButton} from '@rmwc/dialog'
import {act, fireEvent, render} from '@testing-library/react'

test('DialogButton disabled', () => {
  const {getByText} = render(
    <DialogButton disabled>Disabled Button</DialogButton>,
  )
  expect(getByText('Disabled Button')).toBeDisabled()
})

```

### What you did:

I tried to migrate my codebase to recent @rmwc/dialog and @testing-library/jest-dom

### What happened:

> Error: expect(element).toBeDisabled()
> 
> Received element is not disabled:
>   <span class="mdc-button__label" />
>     at Object.<anonymous> (/Users/p35/PycharmProjects/bug-to-be-disabled/js/Components/Team/PaymentTab.test.jsx:20:40)
>     at Object.asyncJestTest (/Users/p35/PycharmProjects/bug-to-be-disabled/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
>     at /Users/p35/PycharmProjects/bug-to-be-disabled/node_modules/jest-jasmine2/build/queueRunner.js:47:12
>     at new Promise (<anonymous>)
>     at mapper (/Users/p35/PycharmProjects/bug-to-be-disabled/node_modules/jest-jasmine2/build/queueRunner.js:30:19)
>     at /Users/p35/PycharmProjects/bug-to-be-disabled/node_modules/jest-jasmine2/build/queueRunner.js:77:41
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-5lnci?file=/src/__tests__/bug-to-be-disabled.js
![image](https://user-images.githubusercontent.com/13823215/88118839-60bab280-cbc7-11ea-8e9c-2ffdf7f0c478.png)

### Problem description:

Earlier, with deps (@testing-library/jest-dom@^5.9.0 and @testing-library/dom@^7.7.3) that code worked nice. With the new version, it fails

### Suggested solution:

isElementOrAncestorDisabled() returns false because canElementBeDisabled() is false for span.

At first, we need to figure out what changed in new versions of those deps. Then we need to come up with a fix.

**Comment by gnapse** [comment]
I see that you are querying for the button using `getByText`. I am not familiar with this library but this looks like a similar situation there used to be with material-ui's buttons. Is it possible that these buttons have their text not directly inside the `button` but inside a `span` that's inside the button? Can you check what element are you getting from `getByText`? Can you switch to use `getByRole('button', { name: 'button label' })` instead?

**Comment by pahan35** [comment]
@gnapse, thanks! Your suggestion works like a charm.

Before update it was
```
getByText('Disabled Button')
```

My workaround was
```
getByText('Disabled Button').closest('button')
```

With your suggestion I have
```
getByRole('button', {name: 'Disabled Button'})
```
which is clearer.

The last question: should we avoid using getByText('button label') in our tests? Or previous behavior will be fixed someday?

**Comment by gnapse** [comment]
> Or previous behavior will be fixed someday?

To be clear, there is nothing to fix. You ask for the element with inner text content being "Click me" and if your buttons render like this:

```jsx
<button>
  <span>Click me</span>
</button>
```

then `getByText` will of course give you the `span` and not the `button`. Then when you ask `jest-dom` to assert that the element is disabled, the `span` is not disabled. There's no way for `getByText` to know that you want a button. It just knows you want an element with the given text, and it delivers the closest one of course. It cannot arbitrarily deliver a parent element.

The way you have solved this is anyway a better way to query for elements. You are being more explicit in stating that you are looking for a button, the querying library with that information now knows that you want the `button` instead of the `span`, and the disabled assertion works. Whenever possible, prefer `getByRole` as it is more semantic than `getByText`.

> should we avoid using getByText('button label') in our tests?

You should avoid using it if there's something more semantic. But it is perfectly ok for when that's not the case. Check out all the possible aria roles to get to know all the situations when a more semantic way of describing what you're querying for exist. But don't feel bad using `getByText` in cases where it works and there's nothing evidently better to do.

**Comment by pahan35** [comment]
@gnapse, thanks for your thorough explanation!
