### ISSUE TITLE
Inconsistent style testing on toHaveStyle

### ISSUE THREAD

**Issue by pedrobw** [testing-library/jest-dom#320]
- `@testing-library/jest-dom` version: "4.2.4"
- `node` version: "14.15.0"
- `npm` (or `yarn`) version: "1.22.5"

Relevant code or config

```javascript
    let messageInput;

    await waitFor(() => {
      messageInput = screen.getByRole("textbox", { name: /message\*/i });

      const messageInputStyle = window.getComputedStyle(
        messageInput.parentElement.children[1]
      );

      expect(messageInputStyle.borderColor).toBe("#f44336");
    });
```

What you did: Tried to test error message on absent input. The Chrome developer tools show the following for the div in question:
```
.MuiOutlinedInput-root.Mui-error .MuiOutlinedInput-notchedOutline {
    border-color: #f44336;
}


.WithStyles\(ForwardRef\(TextField\)\)-root-129 .MuiOutlinedInput-root fieldset {
     ̶b̶o̶r̶d̶e̶r̶-̶c̶o̶l̶o̶r̶:̶ ̶#̶0̶0̶9̶c̶d̶d̶;̶
}

.MuiOutlinedInput-notchedOutline {
     b̶o̶r̶d̶e̶r̶-̶c̶o̶l̶o̶r̶:̶ ̶r̶g̶b̶a̶(̶0̶,̶ ̶0̶,̶ ̶0̶,̶ ̶0̶.̶2̶3̶)̶
}
```
When testing that the TextBox (from material-ui/core v4.11.0) color was red, we got an error, described next.

What happened:

```
expect(received).toBe(expected) // Object.is equality

    Expected: "#f44336"
    Received: "rgba(0, 0, 0, 0.23)"
```

Reproduction repository: (Private repository)

Problem description: The same problem happens with toHaveStyle instead of toBe. Here is the snippet of code for toHaveStyle:

 ```javascript
    await waitFor(() => {
      messageInput = screen.getByRole("textbox", { name: /message\*/i });
    });

    await expect(messageInput.parentElement.children[1]).toHaveStyle(
      "border-color: #f44336"
    );

```

Suggested solution: I'm assuming that you are not finding the proper CSS priority to get the border color (or any other style for that matter). Don't really know how to solve it.

**Comment by gnapse** [comment]
> I'm assuming that you are not finding the proper CSS priority to get the border color

We do not do the finding/resolution of CSS. This lib relies in the browser's `getComputedStyle`. Given that tests often run in jsdom rather than in a real browser, this might one possible source of your problem. If so, there's nothing we can do about it. If we positively identify this to be the problem, then this might be a bug to be reported on jsdom.

Alternatively, the other possible reason is the most common source of problems when people use `toHaveStyle`: CSS stylesheets are not automatically loaded in the context of tests. Say you render a React component in isolation in a test. The minimal HTML document where you render it does not involve all your regular build process, hence it does not have references to the stylesheets that are indeed present when running the full fledged app. There's also nothing we can do about it.

If you still think is none of these two reasons, then please provide a minimal reproducible example in the form of a repo that we can clone and try this out.

For the time being I'm leaning towards closing this issue while we continue the discussion. We can re-open it if needed.
