### ISSUE TITLE
Add eventually chaining or toEventually* set of matchers

### ISSUE THREAD

**Issue by cuongluu8** [testing-library/jest-dom#361]
### Describe the feature you'd like:

I find asserting on elements to appear/disappear following some async action quite common and therefore find that I'm always wrapping the asserting in a `waitFor` block.  So being able to reduce this boilerplate to something like `expect(screen.getByText("Submit")).eventually.toBeInTheDocument()` actually makes it more readable I think.

### Describe alternatives you've considered:

It would be to just use
```
await waitFor(() => expect(screen.getByText("Submit")).toBeInTheDocument());
```

### Teachability, Documentation, Adoption, Migration Strategy:

`.eventually`

This will create a loop around the matcher so it will keep checking the matcher within a set timeout and interval (similar to how waitFor works).

Alternatively,
`.toEventuallyBeInTheDocument`
Similar to `toBeInTheDocument` but will keep check the element within a set timeout and interval (similar to how waitFor would work)

**Comment by gnapse** [comment]
Hi, cool idea that you've got there.

However, I do not think that `expect` works that way. You add custom matchers to `expect`, but I do not think you can add this intermediary `eventually` object from which you can call the custom matchers but with a difference in behavior.

However, I believe that in the case of `toBeInTheDocument` in particular this is already possible in coordination with the testing library querying helpers. That is, using `findBy*` instead of `getBy`. The `findBy*` queries give you a promise on which you can `await`:

```js
expect(await findByText('Submit')).toBeInTheDocument()
```

Does this help with your needs?

**Comment by cuongluu8** [comment]
Thanks for your response.
I do use `findBy*` but normally when I want to wait for something to appear, but I tend to avoid using it in an assertion, just for readability if nothing else.
I've only briefly looked at the code, but in the `toBeInTheDocument` there is a `this.isNot` which I assume comes from the `.not` chained function, which is where I got the idea of having `eventually` chained function.

**Comment by gnapse** [comment]
The `this.isNot` is an internal thing that jest itself provide you inside a custom matcher, so that you can reverse the result if the matcher is being called in its negative form (i.e. `.not.toBeInTheDocument()`). It's not something we invented, nor we can create other such values off of `this` inside the matcher to do cool custom stuff like what you propose. At least to the extent of my knowledge.

I'm going to close this issue, but the discussion can continue.
