### ISSUE TITLE
Version 5.11.10 broke toContainHTML

### ISSUE THREAD

**Issue by Erebos1337** [testing-library/jest-dom#362]
- `@testing-library/jest-dom` version: 5.11.10
- `node` version: v10.19.0
- `yarn` version: 1.22.5
- `@testing-library/react` version: 11.2.6

### Relevant code or config:

```js
const { baseElement } = render('<div class="Loader"><div class="Child"></div></div>');
expect(baseElement).toContainHTML('<div class="Loader">');
```

### What you did:

We are testing that we are rendering a loader by checking if a div with class 'Loader' was rendered.
This div has children which we do not have control over.

### What happened:

Previously the test worked fine, but after upgrading to 5.11.10+ the test started failing.

### Reproduction:

Render two nested divs, then check only for opening tag of outer div.
```js
const { baseElement } = render('<div class="Loader"><div class="Child"></div></div>');
expect(baseElement).toContainHTML('<div class="Loader">');
```

### Problem description:

Investigating the code showed that normalizeHtml adds a closing div tag to the string,
then it doesn't match the rendered html anymore because the div has children.
So, it tries to match ``` <div class="Loader"></div> ```.

Error Message:
```
expect(element).toContainHTML()
    Expected:
      <div class="Loader">
    Received:
      <body><div class="Loader"><div class="Child"></div></div></body>
```

### Suggested solution:

Adding the html to the dom (in normalizeHtml) introduces some unexpected behavior.
The printed error message/jest ouput doesn't reflect such behavior, it's also not documented.

**Comment by gnapse** [comment]
Hi, thanks for your bug report.

I would say in this case, although I agree with you it can be seen as breaking change, that what really happens is you were relying on implicitly unsupported functionality. This matcher happened to match any substring in the HTML because of how it was implemented before this change. But it was never meant to be used that way. It was meant to check fragments of coherent HTML, and not substrings of it.

For instance, before this version change, probably these checks also passed:

```js
const { baseElement } = render('<div class="Loader"><div class="Child"></div></div>');
expect(baseElement).toContainHTML('class="Loader"');
expect(baseElement).toContainHTML('class=');
expect(baseElement).toContainHTML('div class="Loader"');
```

This was never the intention, nor was it documented to be expected. The intention was always that you were expected to pass HTML fragments that needed to be valid HTML. I'm sorry it was never documented either that this was an explicit expectation. But I see little value in supporting this use case.

As stated [in its documentation](https://github.com/testing-library/jest-dom#tocontainhtml):

> Chances are you probably do not need to use this matcher. We encourage testing from the perspective of how the user perceives the app in a browser. That's why testing against a specific DOM structure is not advised.
>
> It could be useful in situations where the code being tested renders html that was obtained from an external source, and you want to validate that that html code was used as intended.

In your case, although I realize it may be a simplified example taken out of context to show us the issue, if you really want to make that check, you might as well do it like this:

```js
const { baseElement } = render('<div class="Loader"><div class="Child"></div></div>');
expect(document.querySelector('.Loader')).toBeInTheDocument()
```

Hope this clarifies the issue a bit. Let me know if you still have issues with this stance, or any other comments about it.

**Comment by Erebos1337** [comment]
Thank you for your quick answer.
We have changed our code and it works perfectly fine.
I think the documentation should reflect the new behavior more clearly, so that others won't run into the same problem.
To me it's not clear from the code or documentation that the string that was passed to the function would be altered that much.

**Comment by gnapse** [comment]
> I think the documentation should reflect the new behavior more clearly, so that others won't run into the same problem.
> To me it's not clear from the code or documentation that the string that was passed to the function would be altered that much.

That's fair. I created #363. Can you comment here if that's ok now? Or let me know and I can improve it.

**Comment by Erebos1337** [comment]
Yup, perfect. Thank you.
