### ISSUE TITLE
`@types/jest` dependency should be changed to `@jest/types`

### ISSUE THREAD

**Issue by kompot** [testing-library/jest-dom#387]
- `@testing-library/jest-dom` version: 5.14.1
- `@types/testing-library__jest-dom` version: 5.14
- `node` version: 14
- `npm` (or `yarn`) version: yarn 1.2

### Problem description:

Looks like Jest v27 types are not supported by `@types/jest` and were moved to `@jest/types`.

### Suggested solution:

Should `@types/testing-library__jest-dom` also consider upgrading this dependency?

As I can see `@jest/types` do support jest < 27. Seems like a safe upgrade.

**Comment by chbdetta** [comment]
+1. Looks like `@types/testing-library__jest-dom` depends on `pretty-format@26.6.2` and if `jest` is upgraded to v27, the two different version of `pretty-format` is causing problem possibly because `pretty-format@27.0.6` exports a different value

**Comment by markusv** [comment]
any progress on this? This is starting to turn into a problem for us

**Comment by gnapse** [comment]
@markusv I may be able to take care of this in a week or two. But maybe you could take a shot at it? You are welcome to make a pull request contributing this change, and I'll gladly review and release when it's all good.

**Comment by sheremet-va** [comment]
Having types in dependencies is actually making conflict with Vitest: https://github.com/testing-library/jest-dom/issues/427

**Comment by kgregory** [comment]
Issue has resurfaced with breaking changes introduced with Jest 28.  `@types/jest` hasn't been updated yet, this causes a type error since `@testing-library/jest-dom` uses `@types/jest` v27:

```js
	jest.useFakeTimers({
		legacyFakeTimers: true,
	});
```

**Comment by rose-m** [comment]
We've also recently encountered typing issues due to the conflict of Jest 28 vs. the `@types/jest` things that are referenced from `@testing-library/jest-dom`. Especially with the issue that the `mocked` helper previously in `ts-jest/utils` was moved to `jest` directly. Jest states to use `import { jest } from '@jest/globals';` - however, this will then break `jest.mock` usage somehow (not sure why).

To work around this I'm using a `jest.ts` that get's included with the following namespace augmentation:
```
import type { jest as globalJest } from '@jest/globals';

declare global {
  namespace jest {
    const mocked: typeof globalJest.mocked;
  }
}
```
Maybe this helps someone...

**Comment by nickmccurdy** [comment]
`@jest/types` is not a replacement for `@types/jest`. `@jest/types` exposes some TypeScript types for internal Jest packages so external packages can use them, but it does not provide global types or config types, so that would break tests.

I'm going to close this for now as I don't see a need for us to use `@jest/types` for this purpose, and removing `@types/jest` would be a potentially confusing breaking change.
