### ISSUE TITLE
toBeDisabled accepts form tags and roles

### ISSUE THREAD

**Issue by drichard-nexapp** [testing-library/jest-dom#446]
### Describe the feature you'd like:

Some library like downshift allow element like div to have form roles. It could be nice to add roles in the accepted roles that works  with. toBeDisabled

### Suggested implementation:

I could consider role as form tag

### Describe alternatives you've considered:

toHaveAttribute("disabled") instead but it is repetitive

### Teachability, Documentation, Adoption, Migration Strategy:

```
function canElementBeDisabled(element) {
  const tag = getTag(element)
  const role = getRole(element)
  return FORM_TAGS.includes(tag) || FORM_TAGS.includes(role) || isCustomElement(tag)
}
```

**Comment by gnapse** [comment]
It is intentional that we only consider the `disabled` attribute on certain elements. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled)

> The disabled attribute is supported by [<button>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button), [<command>](), [<fieldset>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset), [<keygen>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/keygen), [<optgroup>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup), [<option>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option), [<select>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select), [<textarea>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) and [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input).

Hence, [we deliberately only consider these elements as disabled when the `disabled` attribute is present](https://github.com/testing-library/jest-dom/blob/4d0ceeb3ef140bf924a9ffc7665b6996e1ea6961/src/to-be-disabled.js#L3-L12). The presence of that attribute in any other element is not really disabling anything.

Does that make sense? Am I missing something from your proposal?

**Comment by drichard-nexapp** [comment]
Make sense, thanks you
