### ISSUE TITLE
@types/testing-library__jest-dom ^5.9.1 has jest * in deps and it brokes yarn install

### ISSUE THREAD

**Issue by olegKusov** [testing-library/jest-dom#476]
Please, set fixed version of @types/jest in deps of @types/testing-library__jest-dom because latest @types/jest 29 installs latest expect "^29.0.0". and "expect" package has node engine requirement that does not support node 12.18.1 and it broke our installation

**Comment by wagnerlduarte** [comment]
> 

The same problem here! Did someone fix it?

**Comment by wagnerlduarte** [comment]
> Please, set fixed version of @types/jest in deps of @types/testing-library__jest-dom because latest @types/jest 29 installs latest expect "^29.0.0". and "expect" package has node engine requirement that does not support node 12.18.1 and it broke our installation

Hey @olegKusov!
I solved this problem using a resolution in my `package.json` that override the sub-packages to the same version.

```
  "dependencies": {
     ...
  },
  "resolutions": {
    "@types/jest": "^27.4.0"
  },
```

https://classic.yarnpkg.com/en/docs/selective-version-resolutions

**Comment by orofbrown** [comment]
This causes another issue, though. If you want to use the [recommended setup from the Jest docs](https://jestjs.io/docs/getting-started#type-definitions) and leverage `@jest/globals` instead of `@types/jest`, you can't, because this library is forcing the latter to be installed. So you end up with 2 versions of types to pick from, which makes things really confusing, and adds a lot of redundancy to a project. It would be best if that dependency could just be removed
