### ISSUE TITLE
Cost effective lodash

### ISSUE THREAD

**Issue by nike1v** [testing-library/jest-dom#592]
Please replace lodash with it's smaller representatives, there are only 4 imports, this shouldn't take long.
Appreciate it!

**Comment by gnapse** [comment]
Contributions are welcome on this one. I'm unlikely to do it anytime soon.

Also, since jest-dom is not normally used in a production web app, but in the development environment only, the bundle size is of less concern. But I'm open to doing better.

Idea: we could cross-reference our use of lodash with https://youmightnotneed.com/lodash/

**Comment by gnapse** [comment]
Closed via https://github.com/testing-library/jest-dom/pull/593
