### ISSUE TITLE
Drop an unused @babel/runtime dependency

### ISSUE THREAD

**Issue by aleks-elkin** [testing-library/jest-dom#614]
### Describe the feature you'd like:

Recently, the [Ecosystem Performance](https://e18e.dev/) was formed to cleanup, speedup, levelup the JavaScript Ecosystem.
Socket Security team wrote a blog post about it https://socket.dev/blog/javascript-community-launches-e18e-initiative-to-improve-ecosystem-performance

I noticed that there is a dependency `@babel/runtime` but I did not find any usage of it. I tried locally to remove it and all tests are passing and build command is working.

This dependency adds around 240kb to node_modules which sounds not that big, but considering that `@testing-library/jest-dom` has almost 11 million weekly downloads I believe this change will have an impact on the JS ecosystem.
<img width="538" alt="pkg-size @testing-library:jest-dom" src="https://github.com/user-attachments/assets/0bf47927-e385-45ef-8645-1f1cf0dc2cf4">
Screenshot is taken from the [pkg-size.dev](https://pkg-size.dev/@testing-library%2Fjest-dom)

### Suggested implementation:
Remove the `@babel/runtime` as a dependency.

### Describe alternatives you've considered:
As I understand from the docs of `@babel/runtime`, it should be used on a build stage, so it can be moved to a devDependency if it is actually needed, so end users will not load this to their node_modules on each install.

### Teachability, Documentation, Adoption, Migration Strategy:

I'm willing to send a PR for this 😊

**Comment by gnapse** [comment]
> I'm willing to send a PR for this 😊

Please do. Thanks!

**Comment by billyjanitsch** [comment]
I think you've misunderstood the `@babel/runtime` docs. They [specifically note](https://babeljs.io/docs/babel-runtime#usage) that the package is supposed to be a runtime dependency. It's expected that you won't find uses of the package in the source code, because references to it are injected at build time by [`@babel/plugin-transform-runtime`](https://babeljs.io/docs/babel-plugin-transform-runtime) to avoid adding inline helpers to every transpiled module.

**Comment by billyjanitsch** [comment]
The `@babel/runtime` docs mention that this package is [supposed to be a runtime dependency](https://babeljs.io/docs/babel-runtime#usage). It's an atypical package because rather than being referenced directly in source code, references to it are injected into the transpiled output during the build step by [`@babel/plugin-transform-runtime`](https://babeljs.io/docs/babel-plugin-transform-runtime). The purpose of the package is to avoid Babel adding inline helpers to every transpiled module. So the net effect is to reduce bundle size rather than increase it.

It should only be removed as a dependency if this project stops using Babel to transpile itself.
